hypothesis:
  max_examples: 50

# require OpenZepplin Contracts
dependencies:
  - OpenZeppelin/openzeppelin-contracts@2.5.1
  - OpenZeppelin/openzeppelin-contracts@3.1.0

compiler:
  solc:
    remappings:
      - "@openzeppelinV2=OpenZeppelin/openzeppelin-contracts@2.5.1"
      - "@openzeppelinV3=OpenZeppelin/openzeppelin-contracts@3.1.0"
