on:
  push:

name: Lint

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out github repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Cache node
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Install dependencies
        run: npm i

      - name: Run linter on *.sol
        run: npm run lint:check

      - name: Run solhint
        run: npm run solhint

      - name: Set up python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Slither
        run: pip install slither-analyzer

      - name: Run Slither
        env:
          INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
        # generate .secret, store placeholder private key.
        # NEVER USE THIS private key IN PRODUCTION
        run: |
          echo 06802b60b0c116d3f58f1b3c0fa69c636b1c61913b5f068863b048252236d8ec > .secret
          slither . || true
