on:
  push:
  pull_request:
  # schedule:
  #   # run this workflow every Monday at 1PM UTC
  #   - cron: "* 13 * * 1"

name: local test workflow

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v1

      - name: Npm install
        env:
          NODE_OPTIONS: --max-old-space-size=4096
        run: npm install

      - name: Compile
        env:
          NODE_OPTIONS: --max-old-space-size=4096
        run: npm run compile

      - name: Generate types
        env:
          NODE_OPTIONS: --max-old-space-size=4096
        run: npm run types

      - name: Start Ganache
        run: |
          ganache-cli > /dev/null 2>&1 & sleep 10

      - name: Run unit test
        run: npm run test:unit
      #   # env:
      #   #   NODE_OPTIONS: --max-old-space-size=1024
      # - name: Run integration test
      #   run: npm run test:integration
      #   # env:
      #   #   NODE_OPTIONS: --max-old-space-size=1024
