on:
  push:
  schedule:
    # run this workflow every Saturday at 8AM UTC
    - cron: "* 8 * * 6"

name: mainnet test workflow

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v1

        - name: Install Ganache
          run: npm install -g ganache-cli@6.8.2

        # - name: Npm install
        #   run: npm install

      - name: Test mainnet fork
        # run: |
        #     ganache-cli \
        #     --fork https://mainnet.infura.io/v3/$INFURA_API_KEY \
        #     --unlock $STABLE_COIN_HOLDER \
        #     --unlock $DAI_WHALE \
        #     --unlock $USDC_WHALE \
        #     --unlock $USDT_WHALE \
        #     --unlock $CHI_WHALE \
        #     --networkId 999 &
        #     sleep 10
        #     echo HERE
        run: |
            echo HERE
            echo HERE
        env:
          INFURA_API_KEY: $${{ secrets.INFURA_API_KEY }}
          ETHERSCAN_API_KEY: $${{ secrets.ETHERSCAN_API_KEY }}
          STABLE_COIN_HOLDER: 0x86d10751B18F3fE331C146546868a07224A8598B
          DAI_WHALE: 0x6DCb8492B5De636fD9e0a32413514647D00eF8D0
          USDC_WHALE: 0x8cee3eeab46774c1CDe4F6368E3ae68BcCd760Bf
          USDT_WHALE: 0xBE0eB53F46cd790Cd13851d5EFf43D12404d33E8
          CHI_WHALE: 0x5B1fC2435B1f7C16c206e7968C0e8524eC29b786

    #   - name: Run unit test
    #     run: npm run test:unit
